---
# tasks file for configure-python3

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install python3-requests
  apt:
    name: python3-requests
    state: present
